# CMSC 197 Lec1.1 Quiz 1

Joseph Victor Sumbong

Import matplotlib and numpy

In [1]:
%pylab inline

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


###   Create 2 2D arrays, y_hat and y 
<ul>   y_hat --- !𝑦! </ul>
<ul>   y --- (𝑦! ) </ul>

### Initialize y_hat with 20 linearly spaced numbers between -1 and 1 
### Initialize y with 20 linearly spaced numbers between 0 and 1 

In [2]:
#Using np.linspace() to have linearly spaced numbers
y_hat = np.linspace(-1, 1, num=20)
y = np.linspace(0, 1, num=20)

#Show the arrays
print("y_hat\n", y_hat)
print("y\n", y)

y_hat
 [-1.         -0.89473684 -0.78947368 -0.68421053 -0.57894737 -0.47368421
 -0.36842105 -0.26315789 -0.15789474 -0.05263158  0.05263158  0.15789474
  0.26315789  0.36842105  0.47368421  0.57894737  0.68421053  0.78947368
  0.89473684  1.        ]
y
 [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


### Compute for the shape and dimension of y_hat and y.

In [3]:
#Showing shapes of each array using .shape
print("Shape of y_hat and y")
print("y_hat:", y_hat.shape, "\ny    :", y.shape)

#Showing dimension of y_hat and y using .ndim
print("\nDimension of y_hat and y")
print("y_hat:", y_hat.ndim, "\ny    :", y.ndim)

Shape of y_hat and y
y_hat: (20,) 
y    : (20,)

Dimension of y_hat and y
y_hat: 1 
y    : 1


### Create individual functions for each of the loss functions with y and y_hat as parameters

### Mean Squared Error Function

In [4]:
#function for Mean Squared Error
#Parameters:
#   y_h_vals -> y_hat values
#   y_vals -> y values
#Return L -> Loss value
#Internal Variables:
#     sq_sum = summation of the squares of the difference of y_hat and y

def MSE(y_h_vals, y_vals):
    sq_sum = np.sum((y_h_vals - y_vals) ** 2)
    L = sq_sum / y_vals.size
    return L

### Mean Absolute Error Function

In [5]:
#function for Mean Absolute Error
#Parameters:
#   y_h_vals -> y_hat values
#   y_vals -> y values
#Return L -> Loss value
#Internal Variables:
#     ab_sum = summation of the absolute values of the result of y_hat - y

def MAE(y_h_vals, y_vals):
    ab_sum = np.sum(np.abs((y_h_vals - y_vals)))
    L = ab_sum / y_vals.size
    return L


### Mean Squared Logarithmic Error Function

In [6]:
#function for Mean Squared Logarithmic Error
#Parameters:
#   y_h_vals -> y_hat values
#   y_vals -> y values
#Return L -> Loss value
#Internal variables:
#    a -> result of log of y_h_vals + 1
#    b -> result of log of y_vals + 1
#    log_sum = Summation of the difference of the log results raised by 2

def MSLE(y_h_vals, y_vals):
    a = np.log(y_h_vals + 1)
    b = np.log(y_vals + 1)
    log_sum = np.sum((a-b) ** 2)
    L = log_sum / y_vals.size
    return L

### Mean Absolute Percentage Error Function

In [7]:
#function for Mean Absolute Percentage Error
#Parameters:
#   y_h_vals -> y_hat values
#   y_vals -> y values
#Return L -> Loss value
#Internal Variables:
#     ab_sum = summation of the absolute value of the result of (y_hat - y)/y

def MAPE(y_h_vals, y_vals):
    ab_sum = np.sum(np.abs((y_h_vals - y_vals)/y_vals))
    L = (ab_sum / y_vals.size) * 100
    return str(L)+"%"
    

### Each function should return the loss value (L)

In [8]:
#Showing that each function returns a value
print("Loss Value of y_hat and y")
print("Mean Squared Error: ", MSE(y_hat, y))
print("Mean Absolute Error: ", MAE(y_hat, y))
print("Mean Squared Logarithmic Error: ", MSLE(y_hat, y))
print("Mean Absolute Percentage Error: ", MAPE(y_hat, y))

Loss Value of y_hat and y
Mean Squared Error:  0.3421052631578948
Mean Absolute Error:  0.4999999999999999
Mean Squared Logarithmic Error:  inf
Mean Absolute Percentage Error:  inf%


C:\Users\Victor\AppData\Local\Temp\ipykernel_14428\18922168.py:12: RuntimeWarning: divide by zero encountered in log
  a = np.log(y_h_vals + 1)
C:\Users\Victor\AppData\Local\Temp\ipykernel_14428\2052959076.py:10: RuntimeWarning: divide by zero encountered in true_divide
  ab_sum = np.sum(np.abs((y_h_vals - y_vals)/y_vals))


<p>As can be from the results above, Mean Squared Error and Mean Absolute Error shows a numerical result from our y_hat and y values. However, Mean Squared Logarithmic Error results into inf or infinity. This is because MSLE required that the values of y_hat and y are non-negative numbers and with our y_hat having negative numbers it therefore cannot calculate a numerical result and will return an inf value. In the case of MAPE, our y array contains a 0 which can not be a denominator and because our formula has y as a denominator, it therefore will not compute and return an inf. </p>

## Part 2

<ol>1. Create a 1d array M {1, 2, ...16} using the arange function</ol>

In [9]:
M = np.arange(1, 17) #Passing argument (1, 17) so that it starts with 1 and ends with 16
M

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

<ol>2. Reshape M into 4x4 array and store it to N</ol>

In [10]:
N = M.reshape(4,4)
N

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

<ol>3. Get the 2 nd row of N</ol>

In [11]:
N[1, 0:] #slicing 2nd row under all the columns

array([5, 6, 7, 8])

<ol>4. Get the minimum values for each column of N</ol>

In [12]:
np.min(N, axis = 0) #add argument axis = 0 so that it finds the min by column

array([1, 2, 3, 4])

<ol>5. Get the locations of the minimum values for each column of N</ol>

In [13]:
N.argmin(axis=0) #add argument axis = 0 so that it finds the location by column

array([0, 0, 0, 0], dtype=int64)

<ol>6. Get the average of the whole matrix</ol>

In [14]:
np.mean(N)

8.5

<ol>7. Create a vector V with 4 elements, each element is 1</ol>

In [15]:
V = np.ones((4), dtype='int32') #adding dtype='int32' for better formatting
V

array([1, 1, 1, 1])

<ol>8. Take the dot product of N and V</ol>

In [16]:
np.dot(N, V)

array([10, 26, 42, 58])